import React from 'react';
import { AlertCircle, Clock, TrendingUp } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Alert, AlertDescription } from '@/components/ui/alert';

export interface Recommendation {
  title: string;
  impact: string;
  timeline: string;
}

interface AIRecommendationProps {
  recommendations: Recommendation[];
  loading?: boolean;
  sourceText?: string;
}

const AIRecommendations: React.FC<AIRecommendationProps> = ({
  recommendations,
  loading = false,
  sourceText = "These personalized recommendations are generated by AI based on your financial data."
}) => {
  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-32 space-y-4">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-500"></div>
        <p className="text-sm text-muted-foreground">
          Generating personalized recommendations...
        </p>
      </div>
    );
  }

  if (!recommendations || recommendations.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-32 space-y-4">
        <p className="text-sm text-muted-foreground">
          No recommendations available at this time.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="grid gap-4">
        {recommendations.map((recommendation, index) => (
          <Card key={index} className="overflow-hidden border-l-4 border-l-primary">
            <CardContent className="p-4">
              <h5 className="font-semibold text-base mb-3">{recommendation.title}</h5>
              <div className="grid gap-3 text-sm">
                <div className="flex items-start">
                  <div className="bg-muted rounded-full p-1 mr-2 shrink-0 mt-0.5">
                    <TrendingUp className="h-3.5 w-3.5 text-primary" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground font-medium mb-1">Impact</p>
                    <p className="text-sm leading-relaxed">{recommendation.impact}</p>
                  </div>
                </div>
                <div className="flex items-start">
                  <div className="bg-muted rounded-full p-1 mr-2 shrink-0 mt-0.5">
                    <Clock className="h-3.5 w-3.5 text-secondary" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground font-medium mb-1">Timeline</p>
                    <p className="text-sm leading-relaxed">{recommendation.timeline}</p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
      
      <Alert variant="default" className="mt-6">
        <AlertCircle className="h-4 w-4" />
        <AlertDescription className="text-xs">
          {sourceText}
        </AlertDescription>
      </Alert>
    </div>
  );
};

export default AIRecommendations; 