// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kebioosjmymrwfjpdnfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlYmlvb3NqbXltcndmanBkbmZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjEwOTAsImV4cCI6MjA2MDgzNzA5MH0.9PyuIteRchCPKFZus7dKC5DALIPbkHZ9T1aYemDvyBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);